[tools]
atuin = "18.17.0"
eza = "0.23.5"
fd = "10.4.2"
fzf = "0.74.0"
jq = "1.8.2"
k9s = "0.51.0"
kubectl = "1.36.2"
lazydocker = "0.25.2"
lazygit = "0.63.0"
"aqua:neovim/neovim" = "0.12.4"
opencode = "1.17.18"
ripgrep = "15.1.0"
tmux = "3.7b"
yazi = "26.5.6"
zoxide = "0.10.0"
