[tools]
atuin = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
"aqua:jorgerojas26/lazysql" = "latest"
"aqua:neovim/neovim" = "latest"
opencode = "latest"
ripgrep = "latest"
tmux = "latest"
clang = "latest"
"conda:tree-sitter-cli" = "latest"
yazi = "latest"
zoxide = "latest"
