[tools]
awscli = { version = "latest", symlink_bins = "true" }
bat = "latest"
go = "latest"
node = "latest"
npm = "latest"
helm = "latest"
kubectl = "latest"
terraform = "latest"
java = "latest"
eza = "latest"
python = "latest"
pnpm = "latest"
rust = "latest"
aws-sam-cli = { version = "latest", symlink_bins = "true" }
k9s = "latest"
devcontainer-cli = "latest"
neovim = "latest"
lazydocker = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
lazygit = "latest"
ripgrep = "latest"
"aqua:joshmedeski/sesh" = "latest"
tmux = "latest"
"http:tpm" = { version = "master", url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.tar.gz", strip_components = 1 }
yazi = "latest"
zoxide = "latest"
lua = "latest"
opencode = "latest"
atuin = "latest"
carapace = "latest"
glow = "latest"
"aqua:jorgerojas26/lazysql" = "latest"
clang = "latest"
"conda:tree-sitter-cli" = "latest"
pi = "latest"
