[tools]
awscli = { version = "latest", symlink_bins = "true" }
aws-sam-cli = { version = "latest", symlink_bins = "true" }
devcontainer-cli = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
helm = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
lazydocker = "latest"
neovim = "latest"
ripgrep = "latest"
terraform = "latest"
tmux = "latest"
yazi = "latest"
zoxide = "latest"
